version: "3.8"

services:
  webtop:
    image: lscr.io/linuxserver/webtop:latest
    container_name: webtop
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - SUBFOLDER=/
      - TITLE=Ubuntu Desktop
      - CUSTOM_USER=ubuntu
      - PASSWORD=${PASSWORD:-changeme}
      - DOCKER_MODS=linuxserver/mods:universal-package-install
      - INSTALL_PACKAGES=git|curl|wget|htop|neovim
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - ./config:/config
      - /var/run/docker.sock:/var/run/docker.sock:ro #optional
    shm_size: "1gb"
    restart: unless-stopped